name: meta_defi_flutter
description: A simple Flutter DeFi app integrated with MetaMask.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  walletconnect_dart: ^1.0.3
  web3dart: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
